# Generated by Django 3.0.4 on 2020-04-01 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='JamRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jams.Jam')),
            ],
        ),
        migrations.CreateModel(
            name='JamRequestApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jams.JamRequest')),
            ],
        ),
    ]
