# Generated by Django 3.0.4 on 2020-04-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jam',
            name='open_tok_session',
            field=models.CharField(default='', max_length=250),
        ),
    ]
