# Generated by Django 3.0.4 on 2020-04-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0002_jam_open_tok_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jam',
            old_name='open_tok_session',
            new_name='open_tok_session_id',
        ),
    ]
