# Generated by Django 3.0.4 on 2020-04-03 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jams', '0004_auto_20200401_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='jam',
            name='coordinator',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jamrequest',
            name='publisher',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jam',
            name='open_tok_session_id',
            field=models.CharField(default='2_MX40NjU5MzM4Mn5-MTU4NTg5NTE4NTIwNX5WMTIzaloreGtYYVFZS1VxZmw5RUJXWEx-fg', max_length=250),
        ),
    ]
