# Generated by Django 3.0.4 on 2020-04-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0006_auto_20200404_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jam',
            name='open_tok_session_id',
            field=models.CharField(default='2_MX40NjU5MzM4Mn5-MTU4NjAxODA1MTUwNX54OFNjc000ckE0MnVjMzE1TTdEY1dCTSt-fg', max_length=250),
        ),
    ]
