# Generated by Django 3.0.4 on 2020-04-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0008_auto_20200405_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jam',
            old_name='coordinator',
            new_name='moderator',
        ),
        migrations.AlterField(
            model_name='jam',
            name='opentok_session_id',
            field=models.CharField(default='1_MX40NjU5MzM4Mn5-MTU4NjA1Mzg1MzUwMn5rc09vcEI1NmdIU1ZaNWYwaEdTVjJHVzd-fg', max_length=250),
        ),
    ]
